zookeeper:
  image: aviata/zookeeper
  name: zookeeper
  ports:
    - "2181"
    - "22"
kafka:
  image: aviata/kafka
  name: kafka
  ports:
    - "9092"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
nimbus:
  image: aviata/storm-nimbus-2
  ports:
    - "3773"
    - "3772"
    - "6627"
    - "22"
  links:
    - zookeeper:zookeeper
# The target jar filename is mystuff-discom_2.10.jar
  volumes:
#    - ~/.ivy2/local/com.aviata.mystuff/mystuff-discom_2.10/1.14/jars/:/root/topology/
    - ~/storm-jars/:/root/topology/
    - ~/storm-jars/lib/all-jars/:/opt/apache-storm-0.9.4/lib/
supervisor:
  image: aviata/storm-supervisor
  ports:
    - "8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zookeeper
    - couchbase:couchbase
  volumes:
    - ~/storm-jars/lib/all-jars/:/opt/apache-storm-0.9.4/lib/
ui:
  image: aviata/storm-ui
  ports:
    - "8080:8080"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zookeeper
couchbase:
  image: aviata/couchbase-server
  ports:
    - "8091:8091"
    - "8092"
    - "11210"
    - "11211"
  volumes:
    - /:/hostMount
    - ~/couchbase/export-dev/:/app/backup
mystuff:
  image: aviata/scala-2
  working_dir: /opt/app/mystuff/
  command: sbt -jvm-debug 9999 publish-local "project webApp" run 
  ports:
    - "9000:9000"
    - "9999:9999"
  links:
    - couchbase:couchbase
    - kafka:kafka
    - zookeeper:zookeeper
  volumes:
    - ~:/opt/app
    - /:/testmystuff
    - ~/.m2:/root/.m2
    - ~/.sbt:/root/.sbt
    - ~/.ivy2:/root/.ivy2
  stdin_open: true
  tty: true
mystuffweb:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - mystuff:mystuff
  volumes:
    - ~/mystuff-web/bin:/usr/share/nginx/html/
