zookeeper:
  image: dalekurt/zookeeper
  ports: 
    - "2181"
kafka:
  build: .
  name: kafka
  hostname: kafka 
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "kafka"
    KAFKA_ADVERTISED_PORT: 9092
