app:
  image: dalekurt/scala
  ports:
    - "9000"
  links:
    - couchbase:couchbase
    - kafka:kafka
  volumes:
    - ~/Code/mystuff:/app
zookeeper:
  image: dalekurt/zookeeper
  ports: 
    - "2181"
    - "22"
kafka:
  image: dalekurt/kafka
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
nimbus:
  image: dalekurt/storm-nimbus
  ports:
    - "3773"
    - "3772"
    - "6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: dalekurt/storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
    - couchbase:couchbase
ui:
  image: dalekurt/storm-ui
  ports:
    - "8080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
couchbase:
  image: dalekurt/couchbase-server
  ports:
    - "8091" 
    - "8092"
    - "11210"
    - "11211"
