#FROM aviata/scala
FROM dalekurt/scala
MAINTAINER Dale-Kurt Murray "dalekurt.murray@gmail.com"

RUN mkdir /opt/app

#WORKDIR /app
#ADD ./code /app
#RUN mvn install

#WORKDIR /opt/app/mystuff/mystuff-play-scala-webapp
WORKDIR /opt/app/mystuff/
#RUN sbt run

EXPOSE 9000

#FROM dalekurt/scala
#MAINTAINER Dale-Kurt Murray "dalekurt.murray@gmail.com"

#CMD "echo" "part 1"

#RUN mkdir /app

#WORKDIR /app
#ADD ./code /app
#RUN mvn install

#WORKDIR /opt/app/mystuff/mystuff-play-scala-webapp
#CMD "sbt" "run"
# RUN sbt run

#CMD "echo" "part 2"

#EXPOSE 9000
